#!/usr/bin/env bash
mysqldump \
    --skip-opt \
    --single-transaction \
    --disable-keys --extended-insert --quick --set-charset \
    --no-create-db \
    --create-options --hex-blob \
    --skip-comments --log-error=dump-log-error.log \
    --add-drop-table \
    "$@" \

#    --result-file=auth.sql \
#    --default-character-set=utf8mb4 \
# --host=localhost --port=port_num --user=user_name --password=password \
# --opt:  --add-drop-table --add-locks --create-options --disable-keys --extended-insert --lock-tables --quick --set-charset